source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'CinematX' do
    use_frameworks!
    pod 'Swinject'
    pod 'SwinjectStoryboard'
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'Microfutures'
end